"""add complexity to symbols

Revision ID: 0cc6131ac5a6
Revises: fccc7b331f0f
Create Date: 2026-08-21 12:00:39.400512

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0cc6131ac5a6'
down_revision: str | None = 'fccc7b331f0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL needs a server default: symbols rows already exist, and adding a
    # non-nullable column without one fails outright. The default is 1 (the
    # complexity of a straight-line body) rather than 0, which is not a value
    # McCabe can produce. Rows written before this migration keep that 1 until
    # the repository is re-parsed, so a repo parsed earlier reads as uniformly
    # trivial rather than as missing — worth knowing when reading old findings.
    op.add_column(
        'symbols',
        sa.Column('complexity', sa.Integer(), nullable=False, server_default='1'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'complexity')
    # ### end Alembic commands ###
