"""add stage_ms to parse_jobs

Hand-written rather than autogenerated: this arrived during the Week 5
performance pass while the local database was down, so `--autogenerate` had
nothing to diff against. The column is a single JSONB map of stage name to
milliseconds, which is why one column covers all five stages and adding a sixth
needs no migration at all.

Revision ID: 4e21c7b9a30f
Revises: 0cc6131ac5a6
Create Date: 2026-09-02

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4e21c7b9a30f'
down_revision: str | None = '0cc6131ac5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL with a server default: parse_jobs rows already exist, and an
    # empty map is the honest value for a run that finished before stage timing
    # was recorded — it says "not measured", where zeros would claim the stages
    # took no time.
    op.add_column(
        'parse_jobs',
        sa.Column(
            'stage_ms',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )


def downgrade() -> None:
    op.drop_column('parse_jobs', 'stage_ms')
