"""create source_files and symbols tables

Revision ID: 7b66ffa8c249
Revises: 433a47f5bfc2
Create Date: 2026-08-13 14:22:54.662667

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7b66ffa8c249'
down_revision: str | None = '433a47f5bfc2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('module', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('import_count', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_files_repo_path', 'source_files', ['repository_id', 'path'], unique=True)
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qualname', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('module', sa.Text(), nullable=True),
    sa.Column('parent', sa.Text(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('returns', sa.Text(), nullable=True),
    sa.Column('is_async', sa.Boolean(), nullable=False),
    sa.Column('decorators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbols_file', 'symbols', ['file_id'], unique=False)
    op.create_index('ix_symbols_repo_qualname', 'symbols', ['repository_id', 'qualname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symbols_repo_qualname', table_name='symbols')
    op.drop_index('ix_symbols_file', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_source_files_repo_path', table_name='source_files')
    op.drop_table('source_files')
    # ### end Alembic commands ###
