"""create parse_jobs table

Revision ID: a1b08af925a7
Revises: 7b66ffa8c249
Create Date: 2026-08-17 11:41:15.811117

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a1b08af925a7'
down_revision: str | None = '7b66ffa8c249'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_stage', sa.String(length=20), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('import_count', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('failed_file_count', sa.Integer(), nullable=False),
    sa.Column('graph_nodes', sa.Integer(), nullable=False),
    sa.Column('graph_relationships', sa.Integer(), nullable=False),
    sa.Column('graph_nodes_deleted', sa.Integer(), nullable=False),
    sa.Column('graph_relationships_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_jobs_repo_created', 'parse_jobs', ['repository_id', 'created_at'], unique=False)
    op.create_index('ix_parse_jobs_run', 'parse_jobs', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parse_jobs_run', table_name='parse_jobs')
    op.drop_index('ix_parse_jobs_repo_created', table_name='parse_jobs')
    op.drop_table('parse_jobs')
    # ### end Alembic commands ###
