"""add embedding columns to parse_jobs

Revision ID: a7a0a5d1aeb4
Revises: a1b08af925a7
Create Date: 2026-08-17 12:13:21.991340

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a7a0a5d1aeb4'
down_revision: str | None = 'a1b08af925a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default is required on the NOT NULL columns: parse_jobs already
    # holds rows from Week 2, and Postgres has no value to put in them
    # otherwise. `embedding_model` stays nullable on purpose — NULL is what
    # distinguishes "the embedding pass was skipped" from "it ran and found
    # nothing", which is the normal state without an embedding key.
    op.add_column(
        'parse_jobs',
        sa.Column('chunk_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'parse_jobs',
        sa.Column('embedding_tokens', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('parse_jobs', sa.Column('embedding_model', sa.String(length=64), nullable=True))
    op.add_column(
        'parse_jobs',
        sa.Column('vectors_deleted', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parse_jobs', 'vectors_deleted')
    op.drop_column('parse_jobs', 'embedding_model')
    op.drop_column('parse_jobs', 'embedding_tokens')
    op.drop_column('parse_jobs', 'chunk_count')
    # ### end Alembic commands ###
